[main]
term=xterm-256color
# Uncomment below line for non-DPI-aware mode
#font=JetBrainsMono Nerd Font:size=10
font=JetBrainsMono Nerd Font:size=6
dpi-aware=yes
initial-window-size-chars=120x32

# TODO: Find out the ideal number of these.
workers=8

[bell]
urgent=yes
visual=yes

[scrollback]
lines=10000

[cursor]
style=underline
unfocused-style=unchanged
blink=yes
blink-rate=500

[colors]
background=141222
alpha=0.91

regular0=000000
regular1=ff5555
regular2=50fa7b
regular3=effa78
regular4=bd93f9
regular5=ff79c6
regular6=8d79ba
regular7=bfbfbf

bright0=4d4d4d
bright1=ff6e67
bright2=5af78e
bright3=eaf08d
bright4=caa9fa
bright5=ff92d0
bright6=aa91e3
bright7=e6e6e6

dim0=000000
dim1=a90000
dim2=049f2b
dim3=a3b106
dim4=530aba
dim5=bb006b
dim6=433364
dim7=5f5f5f

flash=ff0000
flash-alpha=0.1

